podział na pakiety, podział klasy głównej
andzia0520/-tic-tac-toe-game pull request #12
Opened 2020-08-22 21:26 UTC by andzia0520

podzieliłam projekt na pakiety, podzieliłam klasę główną, ale nie wyświetlają się "znaczki"

2020-08-23 13:46 UTC, marszelun requested changes

2020-08-25 17:36 UTC, marszelun requested changes
Podział na pakiety - fajny, zastanawiam się nad pakietem `interaction`, ale zobaczymy finalnie jak zrealizujesz pozostałe uwagi. Powodzenia!

2020-08-25 17:36 UTC, marszelun commented on kodilla-individual-project/src/main/java/com/kodilla/game/TicTacToe.java
> +        scene.setOnKeyPressed(e -> gameFlow.onKeyPressed(e));
Metoda w `gameFlow` może się nazywać dowolnie, np. `handleKey` ;)

2020-08-25 17:36 UTC, marszelun commented on kodilla-individual-project/src/main/java/com/kodilla/game/flow/GameFlow.java
> +    SignDrawer signDrawer;
`private final`... - wszystkie 3 pola

2020-08-25 17:36 UTC, marszelun commented on kodilla-individual-project/src/main/java/com/kodilla/game/flow/GameFlow.java
> +    ConversionKeyToPosition conversion = new ConversionKeyToPosition();
Warto trzymać pola obok siebie - przenieś to nad konstruktor. + `private final` :)

2020-08-25 17:36 UTC, marszelun commented on kodilla-individual-project/src/main/java/com/kodilla/game/flow/GameFlow.java
> +        signDrawer.addSign(computerPosition, new Circle());
Te 2 linie się powtarzają - warto je wydzielić do metody, z dwoma argumentami - `int position` i `Sign sign`.
Przekazanie obiektu `Circle` lub `Cross` możesz zrobić np. `sign == Sign.CIRCLE ? new Circle() : new Cross()`

2020-08-25 17:36 UTC, marszelun commented on kodilla-individual-project/src/main/java/com/kodilla/game/graphic/Circle.java
> +    //@Override
Do wyrzucenia :)

2020-08-25 17:36 UTC, marszelun commented on kodilla-individual-project/src/main/java/com/kodilla/game/graphic/Cross.java
> +    //@Override
Do wyrzucenia :)

2020-08-25 17:36 UTC, marszelun commented on kodilla-individual-project/src/main/java/com/kodilla/game/graphic/GraphicSign.java
> +    //abstract public boolean isCross();
Do wyrzucenia :)

2020-08-25 17:36 UTC, marszelun commented on kodilla-individual-project/src/main/java/com/kodilla/game/graphic/SignDrawer.java
> +    public void showGameResult(GameResult gameResult) {
Unikamy ifów w miarę możliwości, zwłaszcza że podobne ify masz już w `GameFlow`.
Lepiej zrobić 3 metody, każdą dedykowaną do jednego rodzaju komunikatu.

2020-08-25 17:36 UTC, marszelun commented on kodilla-individual-project/src/main/java/com/kodilla/game/graphic/SignDrawer.java
> +        Alert alert = new Alert(Alert.AlertType.INFORMATION);
Unikamy wstawiania blokującego kodu w konstruktor. Akurat tutaj to zadziała, ale w bardziej złożonym środowisku czy frameworku, może to spowodować zblokowanie całego kodu inicjalizującego framework (np. beany springowe - jak w konstruktorze wstawisz coś co blokuje wątek do czasu akcji użytkownika, cała reszta frameworka stoi i czeka, a mogą się w tym czasie inicjalizować inne komponenty).

Przenieś proszę ten alert do odrębnej metody. Poszukaj eventu, który dzieje się np.  po załadowaniu sceny - z pewnością coś się w JavaFx znajdzie :)

2020-08-25 17:36 UTC, marszelun commented on kodilla-individual-project/src/main/java/com/kodilla/game/TicTacToe.java
> +    GameFlow gameFlow = new GameFlow(signDrawer, gameState, computersLogic);
Zauważ, że 3 powyższe obiekty nie są do niczego potrzebne w `TicTacToe` - mogłyby być tworzone w `GameFlow`.
Jednak podoba mi się obecna wersja - takie domowej roboty dependency injection, wygląda to prawie jak beany springowe :D

2020-08-25 17:36 UTC, marszelun commented on kodilla-individual-project/src/main/java/com/kodilla/game/flow/GameFlow.java
> +import javafx.scene.input.KeyEvent;
Tutaj widać, że `GameFlow` zależy od biblioteki JavaFX. Można usunąć tę zależność - przenieść konwersję `KeyEvent` na nr pozycji do odrębnej klasy i używać jej bezpośrednio w `TicTacToe`.
Dzięki temu jeśli postanowisz zmienić JavaFX na Swing, klasa `GameFlow` nie zmieni się ani o jeden przecinek ;)

2020-08-25 21:07 UTC, andzia0520 commented on kodilla-individual-project/src/main/java/com/kodilla/game/flow/GameFlow.java
> +        signDrawer.addSign(computerPosition, new Circle());
tu nie jestem przekonana = w gameState.add argumenty to int position i Sign sign, ale dla w signDrawer .add są int position i GraphicSign graphicSign. poza tym tylko 2 razy to wstawiamy to czy jest sens  kombinować z oddzielną metodą? tym bardziej ze argumenty są różne?

2020-08-26 06:21 UTC, marszelun commented on kodilla-individual-project/src/main/java/com/kodilla/game/flow/GameFlow.java
> +        signDrawer.addSign(computerPosition, new Circle());
Moim zdaniem warto.

2020-08-29 09:03 UTC, marszelun requested changes
Oprócz uwag przy kodzie, brakuje mi jeszcze:
- testów `ConversionKeyToPosition`
- testów `ComputersLogic` - tutaj ze względu na `Random`, można zrobić 2 rodzaje testów - np. test gdy 8 pól jest już wypełnionych (wtedy komputer musi zagrać ostatnie wolne pole), lub test w którym asercja sprawdza, czy zwrócona wartość należy do jednej z pustych pozycji,
- testów `GameFlow`, przynajmniej metody `handleUserChoice` - tutaj możesz użyć Mockito do zweryfikowania, czy został odpowiednio wywołany `gameState` i `signDrawer`.

2020-08-29 21:06 UTC, andzia0520 commented on kodilla-individual-project/src/main/java/com/kodilla/game/TicTacToe.java
> +        gameFlow.playAgain();
nie, bez tego też działa

2020-08-29 21:06 UTC, andzia0520 commented on kodilla-individual-project/src/main/java/com/kodilla/game/graphic/SignDrawer.java
> +    public void showMessage() {
faktycznie, poprawione

2020-08-29 21:08 UTC, andzia0520 commented on kodilla-individual-project/src/main/java/com/kodilla/game/graphic/SignDrawer.java
> +        illegalMovement.setContentText("Please choose only empty fields (use keys 1 - 9)");
poprawione

2020-08-29 21:09 UTC, andzia0520 commented on kodilla-individual-project/src/main/java/com/kodilla/game/flow/GameFlow.java
> +        if (gameState.getGameResult() == GameResult.PLAYER_WON) {
dobry pomysł :)

2020-08-29 22:57 UTC, andzia0520 commented on kodilla-individual-project/src/main/java/com/kodilla/game/graphic/SignDrawer.java
> +        if (result.get() == buttonTypeYES) {
zrobione

2020-08-29 23:00 UTC, andzia0520 commented on kodilla-individual-project/src/main/java/com/kodilla/game/flow/GameFlow.java
> +    public void handleUserChoice(Integer position) {
jak rozdzieliłam część do osobnych metod to po rozgrywce i opcji playAgain  na planszy od razu jest jedno kółko w losowym miejscu.....

2020-08-29 23:03 UTC, andzia0520 commented on kodilla-individual-project/src/main/java/com/kodilla/game/flow/GameFlow.java
> +        if (gameState.getGameResult() == GameResult.PLAYER_WON) {
zrobiłam GameResult result = gameState.getGameResult();  jak podstawiam result w metodzie handleUserChoice w GameFlow w  logice gracza działa wszystko, jak zmienię też w logice komputera to przestaje wyświetlać komunikaty jeśli komputer wygra... musiałam przypisać to do dwóch zmiennych. przy logice gracza result, przy logice komputera gameResult

2020-08-30 09:34 UTC, marszelun requested changes

2020-08-30 09:34 UTC, marszelun commented on kodilla-individual-project/src/main/java/com/kodilla/game/TicTacToe.java
> +    private final GameState gameState = new GameState();
Przenieś pola nad metody.

2020-08-30 09:34 UTC, marszelun commented on kodilla-individual-project/src/main/java/com/kodilla/game/flow/GameFlow.java
> +        checkIllegalMovement(position);
Po wydzieleniu nie jest odpowiednik 1:1. Jeśli Twoja metoda sprawdzi niewłaściwy ruch, to tylko wyświetli komunikat, a i tak metoda biegnie dalej.
Powinnaś zwracać z tej metody `boolean` i jeśli zwróci wartość mówiącą o błedzie walidacji - opuścić `handleUserChoice`.
Ewentualnie można też użyć tutaj wyjątku :)

2020-08-30 14:05 UTC, marszelun approved these changes

2020-08-30 14:05 UTC, marszelun commented on kodilla-individual-project/src/main/java/com/kodilla/game/flow/GameFlow.java
> +        if (!isIllegalMovement(position)) {
Tu by moim zdaniem było nieco czytelniej sprawdzić warunek bez negacji, wywołać wtedy ` signDrawer.showIllegalMovement();`, potem `return` i w ogóle bez bloku `else`.

2020-08-31 20:15 UTC, merged